export const feedbackActionTypes = {
  ADD_ITEM_TO_FEEDBACK_QUEUE: 'ADD_ITEM_TO_FEEDBACK_QUEUE',
  REMOVE_ITEM_FROM_FEEDBACK_QUEUE: 'REMOVE_ITEM_FROM_FEEDBACK_QUEUE',
  RENDER_FEEDBACK: 'RENDER_FEEDBACK',
}
